var pants = [];
pants.push({name:"Pants 1", price:25.99, image:"pants1.jpg", inStock:true});
pants.push({name:"Pants 2", price:35.99, image:"pants2.jpg", inStock:false});
pants.push({name:"Pants 3", price:30.99, image:"pants3.jpg", inStock:true});
pants.push({name:"Pants 1", price:25.99, image:"pants1.jpg", inStock:false});
pants.push({name:"Pants 2", price:35.99, image:"pants2.jpg", inStock:true});
pants.push({name:"Pants 3", price:30.99, image:"pants3.jpg", inStock:true});
pants.push({name:"Pants 1", price:25.99, image:"pants1.jpg", inStock:false});
pants.push({name:"Pants 2", price:35.99, image:"pants2.jpg", inStock:true});
pants.push({name:"Pants 3", price:30.99, image:"pants3.jpg", inStock:false});
pants.push({name:"Pants 1", price:25.99, image:"pants1.jpg", inStock:true});
pants.push({name:"Pants 2", price:35.99, image:"pants2.jpg", inStock:true});
pants.push({name:"Pants 3", price:30.99, image:"pants3.jpg", inStock:false});

var shirts = [];
shirts.push({name:"Shirt 1", price:25.99, image:"shirt1.jpg", inStock:true});
shirts.push({name:"Shirt 2", price:35.99, image:"shirt2.jpg", inStock:false});
shirts.push({name:"Shirt 3", price:30.99, image:"shirt3.jpg", inStock:true});
shirts.push({name:"Shirt 1", price:25.99, image:"shirt1.jpg", inStock:true});
shirts.push({name:"Shirt 2", price:35.99, image:"shirt2.jpg", inStock:false});
shirts.push({name:"Shirt 3", price:30.99, image:"shirt3.jpg", inStock:true});
shirts.push({name:"Shirt 1", price:25.99, image:"shirt1.jpg", inStock:true});
shirts.push({name:"Shirt 2", price:35.99, image:"shirt2.jpg", inStock:true});
shirts.push({name:"Shirt 3", price:30.99, image:"shirt3.jpg", inStock:true});
shirts.push({name:"Shirt 1", price:25.99, image:"shirt1.jpg", inStock:false});
shirts.push({name:"Shirt 2", price:35.99, image:"shirt2.jpg", inStock:true});
shirts.push({name:"Shirt 3", price:30.99, image:"shirt3.jpg", inStock:true});

var accessories = [];
accessories.push({name:"Watch 1", price:25.99, image:"acc1.jpg", inStock:true});
accessories.push({name:"Watch 2", price:35.99, image:"acc2.jpg", inStock:true});
accessories.push({name:"Watch 3", price:30.99, image:"acc3.jpg", inStock:false});
accessories.push({name:"Watch 1", price:25.99, image:"acc1.jpg", inStock:true});
accessories.push({name:"Watch 2", price:35.99, image:"acc2.jpg", inStock:true});
accessories.push({name:"Watch 3", price:30.99, image:"acc3.jpg", inStock:true});
accessories.push({name:"Watch 1", price:25.99, image:"acc1.jpg", inStock:false});
accessories.push({name:"Watch 2", price:35.99, image:"acc2.jpg", inStock:true});
accessories.push({name:"Watch 3", price:30.99, image:"acc3.jpg", inStock:true});
accessories.push({name:"Watch 1", price:25.99, image:"acc1.jpg", inStock:true});
accessories.push({name:"Watch 2", price:35.99, image:"acc2.jpg", inStock:false});
accessories.push({name:"Watch 3", price:30.99, image:"acc3.jpg", inStock:true});
